edition = "2018"
enum_discrim_align_threshold = 15
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
normalize_comments = true
wrap_comments = true
