[package]
name = "esp-hal-common"
version = "0.1.0"
edition = "2018"

[dependencies]
embedded-hal = { version = "0.2", features = ["unproven"] }
nb = "1.0"
void = { version = "1.0", default-features = false }
# Each supported device MUST have its PAC included below.
esp32   = { path = "../../esp-pacs/esp32",   optional = true }
esp32c3 = { path = "../../esp-pacs/esp32c3", optional = true }
esp32s2 = { path = "../../esp-pacs/esp32s2", optional = true }

[features]
enable-esp32 = ["esp32"]
enable-esp32c3 = ["esp32c3"]
enable-esp32s2 = ["esp32s2"]
