[package]
name    = "esp32c2-hal"
version = "0.1.0"
authors = [
    "Jesse Braham <jesse@beta7.io>",
    "Björn Quentin <bjoern.quentin@mobile-j.de>",
]
edition      = "2021"
rust-version = "1.60.0"
description  = "HAL for ESP32-C2 microcontrollers"
repository   = "https://github.com/esp-rs/esp-hal"
license      = "MIT OR Apache-2.0"

keywords = [
    "embedded",
    "embedded-hal",
    "esp",
    "esp32c2",
    "no-std",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]

[patch.crates-io]
esp-backtrace = { path = "/Users/jesse/Work/esp-backtrace" }
esp-println   = { path = "/Users/jesse/Work/esp-println" }

[dependencies]
bare-metal     = "1.0.0"
embedded-hal   = { version = "0.2.7", features = ["unproven"] }
embedded-hal-1 = { package = "embedded-hal", version = "=1.0.0-alpha.8" }
r0             = "1.0.0"
riscv          = "0.8.0"
riscv-rt       = { version = "0.9.0", optional = true }

[dependencies.esp-hal-common]
path     = "../esp-hal-common"
features = ["esp32c2"]

[dev-dependencies]
critical-section  = "1.1.0"
embedded-graphics = "0.7.1"
esp-backtrace     = { version = "0.2.0", features = ["esp32c2", "panic-handler", "exception-handler", "print-uart"] }
esp-println       = { version = "0.2.2", features = ["esp32c2"] }
smart-leds        = "0.3.0"
ssd1306           = "0.7.1"

[features]
default     = ["rt", "vectored"]
direct-boot = []
eh1         = ["esp-hal-common/eh1"]
rt          = ["riscv-rt"]
smartled    = ["esp-hal-common/smartled"]
ufmt        = ["esp-hal-common/ufmt"]
vectored    = ["esp-hal-common/vectored"]

[[example]]
name              = "spi_eh1_loopback"
required-features = ["eh1"]
